name: dss
summary: a ML development and experimentation environment manager
description: |
     Some description
adopt-info: dss
base: core22
confinement: strict

plugs:
  dot-dss-config:
    interface: personal-files
    write:
      - $HOME/.dss/config

parts:
  dss:
    plugin: python
    source: .
    override-pull: |
      craftctl default
      craftctl set version="0.1"
      #craftctl set version=$(git describe --tags --abbrev=10)

apps:
  dss:
    command: bin/dss
    plugs:
      - home
      - network
